### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by OmegaMetor** [Name2781/gmsl#1]
![image](https://github.com/Name2781/gmsl/assets/42892531/62ae53db-6253-443a-b53d-26037d96605b)
When I try to launch the game after adding the gsml folder and version.dll to my game's directory, as i have to assume is how you install it due to a lack of any docs, it crashes with this error.

**Comment by robieless** [comment]
Was fixed in 763bbfd but the actions didn't rerun for some reason.
